// <auto-generated />
namespace SCAAD.APIs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CREATEDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CREATEDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201606091042428_CREATEDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
